-- Interview Questions for Role: Java Developer (role_id = 1)
-- Total Questions: 10 (4 Easy, 4 Medium, 2 Hard)

INSERT INTO `questions` (`role_id`, `topic`, `difficulty`, `question_text`, `ideal_answer`) VALUES
(1, 'JDK vs JRE', 'Easy', 'What is the difference between JDK and JRE in Java?', 'The Java Development Kit is a software development environment used to develop Java applications, and it contains tools like compiler and debugger alongside the Java Runtime Environment. On the other hand, the Java Runtime Environment is the implementation of the Java Virtual Machine that provides the minimum requirements for executing Java applications. While developers need the complete development kit to write and compile code, end-users only require the runtime environment to execute compiled bytecode on their systems. Therefore, the development kit is for creation, whereas the runtime environment is purely for execution.'),

(1, 'OOP', 'Easy', 'Explain the concept of Polymorphism in Object-Oriented Programming.', 'Polymorphism is a core concept of object-oriented programming that allows a single interface or reference to represent different underlying forms or behaviors. In Java, this is primarily achieved through method overloading, which is compile-time polymorphism, and method overriding, which represents runtime polymorphism. Method overloading occurs when multiple methods have the same name but different signatures within the same class, whereas method overriding allows a subclass to provide a specific implementation of a method already defined in its parent class. This mechanism enhances flexibility, reusability, and dynamic behavior in application development.'),

(1, 'Strings', 'Easy', 'Why are String objects immutable in Java?', 'String objects are designed to be immutable in Java for several key reasons, including security, memory management, and thread safety. Immutability ensures that strings cannot be altered after creation, which prevents unauthorized modifications to sensitive data like database connection strings or network coordinates. Additionally, the JVM utilizes a string constant pool to share identical literal values among different variables, which saves memory but requires the strings to remain unchanged. Finally, immutable strings are inherently thread-safe because multiple concurrent processes can read them without any risk of data corruption or race conditions.'),

(1, 'Interfaces', 'Easy', 'What is the purpose of an interface in Java, and how does it differ from a class?', 'An interface in Java is a reference type that acts as a contract to define abstract behaviors without providing concrete implementation details. It differs from a class because a class describes the state and behavior of an object, whereas an interface purely declares what an implementing class must do. In Java, a class can inherit from only one superclass, but it can implement multiple interfaces, allowing a flexible form of multiple inheritance. Interfaces cannot be instantiated directly and historically contained only abstract methods, although modern Java versions permit default and static methods to provide basic reusable logic.'),

(1, 'Exception Handling', 'Medium', 'Explain the differences between checked and unchecked exceptions in Java.', 'Checked exceptions are verified by the Java compiler at compile time, meaning the developer is forced to handle them using try-catch blocks or declare them in the method signature using the throws keyword. These exceptions typically represent external conditions beyond the program''s control, such as database connectivity issues or missing files. Unchecked exceptions, which inherit from RuntimeException, are not checked at compile time and usually indicate programming logic errors, such as dividing by zero or accessing a null reference. While checked exceptions represent recoverable conditions, unchecked exceptions usually indicate bugs that should be fixed in code.'),

(1, 'Collections', 'Medium', 'How does a HashMap work internally in Java?', 'A HashMap operates on the principle of hashing, utilizing an internal array of buckets to store key-value pairs as Node objects. When a key-value pair is inserted, Java calculates the hash code of the key using its hashCode method and maps this code to an array index. If multiple keys map to the same bucket index, a collision occurs, which Java resolves by storing colliding elements in a singly linked list at that index. In modern Java versions, if a bucket contains more than eight nodes, the linked list is automatically converted into a balanced tree to ensure faster search performance from linear to logarithmic time complexity.'),

(1, 'JVM', 'Medium', 'Describe the garbage collection process in the Java Virtual Machine.', 'Garbage collection in the Java Virtual Machine is an automatic memory management process that identifies and deletes unused objects to reclaim heap space. The JVM heap is divided into generations, specifically the young generation for short-lived objects and the old generation for long-lived survival objects. A mark-and-sweep algorithm is commonly used where the collector first marks all active objects reachable from GC roots, sweeps the unmarked objects from memory, and optionally compacts the remaining heap space. This process runs in the background, minimizing manual memory allocation efforts and preventing memory leaks in complex applications.'),

(1, 'Multithreading', 'Medium', 'What is the purpose of the synchronized keyword in Java, and how does it prevent race conditions?', 'The synchronized keyword in Java is used to control thread access to shared resources, ensuring that only one thread can execute a critical section of code at any given time. By obtaining an intrinsic lock or monitor on an object, a synchronized method or block prevents race conditions where concurrent threads attempt to read and modify shared data simultaneously, causing inconsistent state. When a thread enters a synchronized zone, all other threads attempting to access the locked resource are blocked and put into a waiting state until the holding thread releases the lock, maintaining thread safety and data integrity.'),

(1, 'Java 8 Features', 'Hard', 'What is the Stream API in Java 8, and how does it differ from traditional collections?', 'The Stream API introduced in Java 8 is a functional programming framework designed for declarative, pipeline-style processing of sequences of elements. Unlike traditional collections, which are in-memory data structures that hold actual elements and focus on storage, a stream is a pipeline that processes data from a source on-demand without storing it. Streams support functional operations like filter, map, and reduce, and execute intermediate operations lazily, meaning evaluation only occurs when a terminal operation is called. This separation allows efficient processing, easier optimization, and parallel execution capabilities without complex multithreading boilerplate.'),

(1, 'Generics', 'Hard', 'Explain the concepts of PECS (Producer Extends, Consumer Super) in Java Generics.', 'The PECS principle stands for Producer Extends, Consumer Super, and is a guideline for using wildcards to design flexible API signatures in Java Generics. If a generic structure produces data of type T for consumption by other code, you should use the extends wildcard, which allows subclasses of T to be accepted. Conversely, if a generic structure consumes data of type T by writing or adding to it, you should use the super wildcard, which accepts superclasses of T to ensure write safety. Applying this rule ensures type-safe read and write operations, maximizing collection compatibility without causing compiler errors.');

-- Total Questions: 20 (8 Easy, 8 Medium, 4 Hard)
INSERT INTO `questions` (`role_id`, `topic`, `difficulty`, `question_text`, `ideal_answer`) VALUES
(1, 'Abstract Classes', 'Easy', 'What is an abstract class in Java, and when should you use it over an interface?', 'An abstract class in Java is a class that cannot be instantiated directly and is declared using the abstract keyword, optionally containing both abstract methods without bodies and concrete methods with complete implementations. Developers should use an abstract class over an interface when they want to share code among several closely related classes, declare non-static or non-final fields, or require full control over state inheritance. It allows subclasses to inherit common state and behavior while forcing them to define specialized operations. Conversely, interfaces are preferred when defining a common contract across unrelated classes.'),

(1, 'Access Modifiers', 'Easy', 'Explain the four types of access modifiers available in Java and their visibility scopes.', 'Java provides four levels of access control to regulate the visibility of classes, constructors, variables, and methods. The private modifier restricts visibility strictly to the defining class itself, ensuring maximum encapsulation. The default or package-private access, which is applied when no modifier is specified, limits visibility to classes within the same package. The protected modifier extends package-private visibility to subclasses in other packages through inheritance. Finally, the public modifier makes the member accessible from any class in any package across the entire application, providing the broadest possible access scope.'),

(1, 'Wrapper Classes', 'Easy', 'What are wrapper classes in Java, and how does autoboxing and unboxing work?', 'Wrapper classes in Java are object representations of primitive data types, allowing primitives like int or char to be used in context-oriented structures like Collections that require objects. Autoboxing is the automatic conversion that the Java compiler performs to turn a primitive type into its corresponding wrapper class object, such as converting an int to an Integer. Unboxing is the reverse process, where the compiler automatically extracts the primitive value from its wrapper object when needed for arithmetic or conditional statements. This seamless translation simplifies coding by blending primitive efficiency with object-oriented capabilities.'),

(1, 'ArrayList vs LinkedList', 'Easy', 'Compare the internal structures and performance characteristics of ArrayList and LinkedList in Java.', 'ArrayList and LinkedList are prominent implementations of the List interface but utilize entirely different internal data structures and performance profiles. An ArrayList is backed by a dynamically resizing array, offering constant time complexity for element retrieval by index but linear complexity for insertions or deletions because elements must be shifted. Conversely, a LinkedList is composed of doubly linked node structures, which require linear time to search or access elements by index but provide constant time for inserting or removing elements once the node location is determined, making them highly efficient for frequent write-heavy operations.'),

(1, 'Comparable vs Comparator', 'Medium', 'What is the difference between the Comparable and Comparator interfaces in Java, and when should you use each?', 'The Comparable interface is used to define the natural ordering of a class''s objects by implementing the compareTo method directly within that class, modifying its source definition. On the other hand, the Comparator interface is used to define custom, multiple sorting orders by implementing the compare method in separate, external helper classes without modifying the target class. Developers should use Comparable when a single, default sorting behavior is universally expected, whereas Comparator is preferred when multiple sorting strategies are required, or when sorting third-party classes whose source code cannot be edited.'),

(1, 'Serialization', 'Medium', 'Explain the process of object serialization and deserialization in Java, and the purpose of the transient keyword.', 'Object serialization in Java is the process of converting an object''s state into a portable byte stream so it can be written to a database, stored in a file, or transmitted over a network. Deserialization is the inverse process of reconstructing the original live object in memory from the serialized byte stream. To enable this behavior, a class must implement the marker Serializable interface. The transient keyword is used to mark member variables that should be excluded from serialization, such as sensitive passwords, temporary session states, or un-serializable references, ensuring they are not saved or transmitted.'),

(1, 'JDBC', 'Medium', 'Describe the core steps required to connect and execute a query on a database using JDBC in Java.', 'To execute a database query using JDBC, a Java application must first register the appropriate database driver to establish a network pathway. Next, it establishes a session connection using the DriverManager class by passing the database URL, username, and password credentials. Once connected, the program creates a Statement or PreparedStatement object to write and encapsulate the SQL query text securely. The query is executed to return a ResultSet object, which acts as a cursor to iterate through retrieved database records. Finally, the application must close the result set, statement, and connection objects to prevent memory resource leaks.'),

(1, 'Optional Class', 'Medium', 'What is the purpose of the Optional class introduced in Java 8, and how does it improve code safety?', 'The Optional class introduced in Java 8 is a generic container object that may or may not contain a non-null value, designed to represent optional values explicitly. It improves code safety by providing a type-level solution to express the potential absence of data, encouraging developers to handle empty cases gracefully instead of writing nested null checks. By using functional methods like map, filter, or orElse rather than directly accessing references, developers can write safer, fluent code that completely avoids throwing NullPointerExceptions, resulting in cleaner and more maintainable software pipelines.'),

(1, 'Functional Interfaces', 'Hard', 'What is a functional interface in Java, and how does it relate to lambda expressions?', 'A functional interface in Java is an interface that contains exactly one abstract method, though it may also define multiple default or static methods. It is optionally annotated with @FunctionalInterface to let the compiler enforce this single-method constraint. Functional interfaces serve as the target types for lambda expressions, which provide a concise inline block of code representing the single abstract method''s implementation. This relationship enables functional programming patterns in Java, allowing developers to pass behavior as arguments to other methods, simplify callback mechanisms, and construct declarative processing pipelines with reduced boilerplate.'),

(1, 'Reflection', 'Hard', 'What is the Reflection API in Java, and what are its primary use cases and performance trade-offs?', 'The Reflection API in Java is a powerful feature that allows an application to inspect, analyze, and modify its own runtime behavior, including classes, methods, fields, and constructors. It is heavily used by popular frameworks like Spring and Hibernate to perform dependency injection, load configuration files, and map database tables to entity fields dynamically without compile-time knowledge. However, reflection introduces noticeable performance overhead because bytecode lookup cannot be optimized by the JVM compiler, and it bypasses access modifiers, raising security risks and compromising structural encapsulation if used carelessly.');

-- Total Questions: 30 (12 Easy, 12 Medium, 6 Hard)
INSERT INTO `questions` (`role_id`, `topic`, `difficulty`, `question_text`, `ideal_answer`) VALUES
(1, 'StringBuilder vs StringBuffer', 'Easy', 'What is the difference between StringBuilder and StringBuffer in Java, and when should you use each?', 'StringBuilder and StringBuffer are both peer classes of String that provide a mutable sequence of characters, but they differ significantly in thread safety and execution performance. StringBuffer is thread-safe because its methods are synchronized, meaning multiple concurrent threads can access it safely without data corruption, which introduces synchronization overhead. In contrast, StringBuilder is not thread-safe because its methods are not synchronized, making it much faster and more efficient for single-threaded environments. Developers should use StringBuilder for general string manipulation within a single thread, and only choose StringBuffer when multiple threads must modify the same string buffer.'),

(1, 'final vs finally vs finalize', 'Easy', 'Explain the differences between the final, finally, and finalize keywords in Java.', 'The final, finally, and finalize keywords in Java serve entirely different purposes in variable declaration, exception handling, and memory cleanup. The final keyword is an access modifier used to make a class non-inheritable, a method non-overridable, or a variable constant so its value cannot be changed after initialization. The finally keyword is a block used in exception handling that executes guaranteed cleanup code after try-catch statements, regardless of whether an exception is thrown or caught. Lastly, finalize is a protected method of the Object class that the garbage collector calls before destroying an object to release system resources, though it is deprecated in modern Java.'),

(1, 'equals() vs hashCode()', 'Easy', 'How do the equals() and hashCode() methods relate to each other in Java, and why is it important to override both?', 'The equals and hashCode methods share a strict contract in Java that is critical for the proper functioning of hash-based collections like HashMap and HashSet. The contract states that if two objects are equal according to the equals method, they must return the same integer hash code from the hashCode method. However, if two objects return the same hash code, they are not necessarily equal. Overriding equals without hashCode violates this contract, causing identical objects to map to different bucket locations within a hash structure, resulting in duplicate elements, retrieval failures, and silent data bugs during collections processing.'),

(1, 'Enum', 'Easy', 'What is an Enum in Java, and what benefits does it provide over standard constants?', 'An enum or enumeration in Java is a special data type used to define a fixed, unchangeable collection of constants, such as days of the week or card suits. Enums are much more powerful than simple constant variables because they are internally compiled as classes, allowing them to possess constructors, instance variables, and custom methods. They provide strong type safety at compile time, preventing developers from passing invalid values to methods, and allow easy iteration over all declared elements using the values method. Consequently, enums improve code readability, self-documentation, and compile-time validation in technical applications.'),

(1, 'Thread Lifecycle', 'Medium', 'Describe the different states in a thread\'s lifecycle in Java and how transitions between them occur.', 'A thread in Java progresses through a defined lifecycle managed by the JVM, starting in the New state when a thread object is instantiated but not yet started. Calling the start method transitions the thread to the Runnable state, where it is eligible to be scheduled for CPU execution. Once executing, a thread can enter the Blocked state when waiting for an intrinsic lock, or the Waiting state when waiting indefinitely for another thread\'s notification. It can also enter the Timed Waiting state during sleep periods. Finally, when the thread completes its execution, it permanently transitions to the Terminated state, releasing all held resources.'),

(1, 'Concurrent Collections', 'Medium', 'What are concurrent collections in Java, and how does ConcurrentHashMap differ from a synchronized HashMap?', 'Concurrent collections are specialized classes in the java.util.concurrent package designed to provide high-performance, thread-safe collection operations in multi-threaded environments. ConcurrentHashMap differs from a synchronized HashMap by utilizing a sophisticated locking mechanism called lock striping or bucket-level locking, rather than locking the entire map container during access. This design allows multiple threads to read and write in different segments of the map concurrently without blocking each other. In contrast, a synchronized HashMap locks the entire object for every operation, causing severe performance bottlenecks as thread competition increases under heavy parallel workloads.'),

(1, 'Lambda Expressions', 'Medium', 'What is a lambda expression in Java, and how does it simplify programming?', 'A lambda expression in Java is a concise representation of an anonymous function that can be passed as an argument or returned as a result, introducing functional programming capabilities to the language. It simplifies programming by allowing developers to implement a functional interface\'s single abstract method inline, completely eliminating the verbose boilerplate code required by anonymous inner classes. Lambda expressions are highly integrated with the Stream API, enabling elegant collection filtering, mapping, and reduction operations in a declarative style. This results in highly readable, expressive, and compact codebases that focus on behavior rather than structural plumbing.'),

(1, 'Custom Exceptions', 'Medium', 'Why would a developer create a custom exception in Java, and how do you implement one?', 'A developer creates a custom exception in Java to represent domain-specific business logic errors that are not adequately described by standard runtime exceptions. Creating custom exceptions improves code readability, debugging accuracy, and diagnostics by providing descriptive error names and contextual details unique to the application\'s use cases. To implement one, a developer creates a new class that extends Exception for a checked exception, or RuntimeException for an unchecked exception, and overrides the constructors to accept error messages and root cause exceptions. This structure allows outer catch blocks to implement specialized error-handling strategies for distinct system failures.'),

(1, 'Executor Framework', 'Hard', 'Explain the Executor Framework in Java and why it is preferred over managing raw threads.', 'The Executor Framework introduced in java.util.concurrent is a robust API that decouples thread creation and execution management from the core application logic. It is highly preferred over creating raw threads manually because it utilizes thread pools to reuse existing threads, eliminating the expensive CPU overhead associated with frequent thread creation and destruction. The framework provides executive services to queue incoming tasks, schedule delayed executions, and manage thread lifecycles automatically under high system concurrency. By configuring optimal thread limits, it prevents resource exhaustion and simplifies asynchronous application design using futures to track task progress and retrieve execution results.'),

(1, 'volatile Keyword', 'Hard', 'What is the purpose of the volatile keyword in Java, and how does it relate to the Java Memory Model?', 'The volatile keyword in Java is a lightweight synchronization mechanism used to ensure variable visibility across concurrent threads according to the Java Memory Model guidelines. By default, threads may cache variables in local CPU registers or caches for performance, leading to data visibility issues where one thread\'s changes are invisible to others. Marking a variable volatile forces all write operations to be flushed directly to main memory, and all read operations to be loaded directly from main memory. This mechanism guarantees that any thread reading the variable always sees the most recent update, preventing stale data bugs without the heavy locking overhead of synchronization.');

-- Total Questions: 40 (16 Easy, 16 Medium, 8 Hard)
INSERT INTO `questions` (`role_id`, `topic`, `difficulty`, `question_text`, `ideal_answer`) VALUES
(1, 'List vs Set vs Map', 'Easy', 'What are the fundamental differences between the List, Set, and Map interfaces in the Java Collections Framework?', 'The List, Set, and Map are core interfaces of the Java Collections Framework designed for different storage requirements. A List is an ordered collection that allows duplicate elements, permitting precise access by index positions. A Set is an unordered collection that prohibits duplicate elements, ensuring uniqueness among its members. Unlike List and Set which extend the Collection interface, a Map represents a mapping of unique keys to values, meaning it stores paired elements rather than single values. Each interface serves different data organization needs, where lists preserve execution order, sets maintain distinct items, and maps facilitate key-based lookups.'),

(1, 'try-with-resources', 'Easy', 'Explain the concept and advantages of the try-with-resources statement in Java.', 'The try-with-resources statement is an exception handling mechanism that automatically closes system resources like database connections, files, and sockets at the end of execution. Any resource declared inside the try parentheses must implement the AutoCloseable or Closeable interface, ensuring that its close method is called when the block exits. This feature significantly simplifies source code readability by eliminating verbose and error-prone finally blocks that were historically required to release system resources. By guaranteeing automatic cleanup even when exceptions occur, try-with-resources prevents severe memory and file lock leaks, making Java enterprise applications robust and secure.'),

(1, 'Annotations', 'Easy', 'What are annotations in Java, and how are they used by compilers and runtime frameworks?', 'Annotations in Java are a form of metadata that provides additional information about code structures like classes, methods, or variables without directly affecting program logic. They are declared using the at symbol and are processed at compile time by the compiler to detect errors or warnings, or at runtime by frameworks to customize application execution. Java provides predefined standard annotations like Override and Deprecated to enforce code safety, as well as meta-annotations to define custom custom tags. Modern frameworks like Spring use runtime annotation reflection to automate dependency injection, manage transaction boundaries, and map HTTP requests dynamically.'),

(1, 'Immutable Objects', 'Easy', 'What is an immutable object in Java, and how can a developer create a custom immutable class?', 'An immutable object is an object whose internal state cannot be modified after it is constructed, guaranteeing complete reliability and thread safety across concurrent applications. To design a custom immutable class, a developer must declare the class as final to prevent inheritance, make all class fields private and final to enforce single assignment, and initialize all variables through a parameterized constructor. Additionally, the class must not provide any setter methods that could change state, and must perform deep cloning when returning references to mutable objects to prevent external tampering. This pattern ensures safe data sharing without defensive copying overhead.'),

(1, 'TreeMap', 'Medium', 'Describe the internal structure and sorting behavior of a TreeMap in Java.', 'A TreeMap is a red-black tree-based implementation of the NavigableMap interface that stores key-value pairs in sorted order determined by the natural ordering of keys or a custom Comparator provided at creation time. This self-balancing binary search tree structure guarantees logarithmic time complexity for basic map operations like put, get, and remove, making it slower than HashMap but invaluable when sorted data retrieval is required. TreeMap does not allow null keys because it relies on key comparison to maintain tree balance, but permits null values. It is ideal for ranges, submaps, and sorted iteration patterns in complex algorithmic pipelines.'),

(1, 'PriorityQueue', 'Medium', 'What is a PriorityQueue in Java, and how does its sorting mechanism differ from a standard FIFO Queue?', 'A PriorityQueue in Java is an unbounded collection based on a priority heap where elements are ordered according to their natural comparison or a custom Comparator specified when initializing the queue. Unlike a standard Queue that processes elements in a strict first-in, first-out order based on insertion time, a PriorityQueue retrieves the highest-priority element first when calling peek or poll. The internal binary heap structure guarantees logarithmic time for insertion and deletion, making it highly efficient. It does not permit null elements and requires all stored objects to be mutually comparable to avoid runtime exceptions, making it ideal for job scheduling algorithms.'),

(1, 'Method References', 'Medium', 'What are method references in Java, and what are the four different types of method references?', 'Method references are a feature introduced in Java 8 that provide a highly readable syntax using the double colon operator to refer to methods or constructors without executing them. They act as shorthand lambda expressions for functional interfaces that simply invoke an existing method, thereby reducing code verbosity. There are four distinct categories of method references in Java, including static method references, instance method references of a specific object, instance method references of an arbitrary object of a particular type, and constructor references. This mechanism allows developers to reuse existing class logic directly, making functional code highly cohesive and elegant.'),

(1, 'File Handling', 'Medium', 'Explain the differences between character streams and byte streams in Java I/O.', 'Java I/O is divided into byte streams and character streams to handle different types of data read and write operations. Byte streams, represented by InputStream and OutputStream classes, process data byte by byte, making them ideal for raw binary files like images, audio, and compiled classes. Character streams, represented by Reader and Writer classes, process data character by character using unicode encodings, making them the preferred choice for text files and documents. While byte streams can handle any file type, character streams automatically manage character encoding translations, preventing data corruption during international text translation across diverse operating platforms.'),

(1, 'Java Memory Model', 'Hard', 'What is the Java Memory Model, and why is it crucial for designing concurrent applications?', 'The Java Memory Model defines the specifications and behaviors of variable sharing across the JVM heap and CPU register caches, establishing rules for thread synchronization and visibility. It is absolutely crucial for concurrent application design because it governs how and when changes made by one thread become visible to other executing threads, preventing memory consistency errors. By defining concepts like happens-before relationships, the model ensures that read and write operations are ordered correctly across multi-core processors. Without the guidelines of the memory model, compilers and processors could aggressively reorder instructions for performance optimization, causing unpredictable, non-deterministic bugs in multithreaded systems.'),

(1, 'Java NIO', 'Hard', 'What is Java NIO (New Input/Output), and how does its architecture differ from standard Java I/O?', 'Java NIO is a high-performance alternative to standard I/O designed to support non-blocking and buffer-oriented file and network communications. While standard I/O uses stream-oriented, blocking operations where threads wait for read and write completion, NIO uses channels and buffers to transfer data in blocks without thread suspension. NIO also utilizes selectors, which allow a single thread to monitor multiple input channels for events like incoming data packets, dramatically reducing thread management overhead. This asynchronous, non-blocking architecture is highly scalable and forms the foundation of modern high-concurrency Java network servers and event-driven frameworks.');

-- Total Questions: 50 (20 Easy, 20 Medium, 10 Hard)
INSERT INTO `questions` (`role_id`, `topic`, `difficulty`, `question_text`, `ideal_answer`) VALUES
(1, 'Static Keyword', 'Easy', 'What is the purpose of the static keyword in Java, and how are static members managed?', 'The static keyword in Java is a non-access modifier used to declare class-level variables, methods, blocks, and nested classes that belong to the class itself rather than instances of the class. This means that static members are shared globally across all instances, and memory for static variables is allocated only once in the JVM metaspace when the class is loaded. Developers can invoke static methods directly using the class name without creating an object, which is highly efficient for utility methods or constant parameters. However, static methods cannot access non-static instance variables directly because they operate outside the scope of individual instances.'),

(1, 'this vs super', 'Easy', 'Explain the differences between the this and super keywords in Java and their typical use cases.', 'The this and super keywords in Java are reference variables used to resolve scope ambiguity between class members and parent class hierarchies. The this keyword represents a reference to the current object instance, and is commonly used to access instance variables when shadowed by local parameter names, or to invoke other overloaded constructors in the same class. Conversely, the super keyword represents a reference to the immediate parent class, and is used to invoke the parent class constructor, call overridden parent methods, or access shadowed parent fields. Together, they enable elegant control over constructor chaining and class inheritance hierarchies.'),

(1, 'Encapsulation', 'Easy', 'What is Encapsulation in Java, and how is it implemented to protect class data?', 'Encapsulation is a fundamental object-oriented programming principle that binds together data and code into a single unit while restricting direct external access to the object\'s fields. In Java, encapsulation is implemented by declaring class variables as private and exposing public getter and setter methods to access and modify those variables safely. This mechanism allows developers to control how data is read or written, enforce validation constraints, and modify internal class implementations without breaking external calling applications. Consequently, encapsulation promotes software security, modularity, and robust structural maintenance in engineering projects.'),

(1, 'Constructor Overloading', 'Easy', 'What is constructor overloading in Java, and why is it useful in application design?', 'Constructor overloading in Java is a design technique that allows a class to have more than one constructor, provided each has a unique parameter list with different numbers, types, or orders of arguments. It enables developers to instantiate objects of the same class in various ways, passing different sets of initial state data depending on the use case. When an object is created, the Java compiler automatically matches the initialization arguments with the corresponding constructor signature. This approach enhances class flexibility and readability, allowing optional configuration parameters without requiring developers to write verbose setter methods immediately after instantiation.'),

(1, 'Method Overloading vs Overriding', 'Medium', 'Compare and contrast method overloading and method overriding in Java.', 'Method overloading and method overriding are both polymorphism techniques in Java but operate under entirely different compilation rules and scopes. Method overloading is compile-time polymorphism that occurs within a single class when multiple methods share the same name but have different parameter signatures, and the compiler determines which method to call based on passed argument types. In contrast, method overriding is runtime polymorphism that occurs between a superclass and a subclass when a child class redefines a parent method with the exact same name, return type, and parameters. The JVM determines which overridden method to execute at runtime based on the actual object type.'),

(1, 'Composition vs Inheritance', 'Medium', 'Explain the difference between composition and inheritance in Java, and why composition is often preferred.', 'Composition and inheritance are two fundamental techniques in Java for extending class behavior, but they establish different relationships between objects. Inheritance represents an is-a relationship where a subclass extends a superclass, acquiring its fields and methods directly, which creates a tight coupling between the parent and child. Composition represents a has-a relationship where a class contains references to instances of other classes as fields, utilizing their behaviors to build complex logic. Software engineering guidelines typically prefer composition over inheritance because it keeps classes loosely coupled, promotes greater runtime flexibility, and avoids violating class encapsulation boundaries.'),

(1, 'BufferedReader vs Scanner', 'Medium', 'Compare the features and performance of BufferedReader and Scanner for reading input in Java.', 'BufferedReader and Scanner are both Java utility classes used to read input, but they have distinct differences in performance, buffering size, and parsing capabilities. BufferedReader is a high-performance reader that utilizes a large internal buffer of eight kilobytes to read characters efficiently, and is preferred for reading raw text data or files rapidly with simple line reads. In contrast, Scanner has a much smaller buffer of one kilobyte and includes built-in parsing capabilities to read and tokenize primitive types and strings using regular expressions. While BufferedReader is faster and thread-safe, Scanner is more convenient for parsing structured, tokenized user console input.'),

(1, 'HashSet', 'Medium', 'How does a HashSet store elements internally, and how does it guarantee uniqueness?', 'A HashSet in the Java Collections Framework is an unordered collection that stores unique elements by utilizing an internal HashMap instance to manage data. When an element is added to a HashSet, it is stored as a key in the backing HashMap with a dummy object as its value. This design ensures constant time complexity for basic operations like add, remove, and contains, because it relies on hashing algorithms to locate elements instantly. HashSet does not preserve any element insertion order and permits a single null element. It relies strictly on hashCode and equals methods to detect duplicates, making duplicate storage impossible.'),

(1, 'Marker Interfaces', 'Hard', 'What is a marker interface in Java, and how does the JVM or a framework use it?', 'A marker interface in Java, also known as a tag interface, is an interface that contains absolutely no methods or constant field declarations. Its primary purpose is to act as a metadata label to deliver run-time or compile-time instructions to the Java Virtual Machine or compiler about an object\'s capabilities. When a class implements a marker interface, such as Serializable, Cloneable, or SingleThreadModel, it advertises that its instances are safe or eligible for specific operations. Frameworks and the JVM use instanceof checks at runtime to discover these tags dynamically, enabling specialized handling, bytecode manipulation, or serialization behaviors without forcing method implementation.'),

(1, 'Cloneable Interface', 'Hard', 'Explain the Cloneable interface in Java, and the difference between shallow and deep copying.', 'The Cloneable interface in Java is a classic marker interface used to indicate that a class legally permits field-for-field copying of its instances. If a class implements Cloneable, the clone method inherited from the Object class can be safely called to create a shallow copy of the target object; otherwise, calling it throws a CloneNotSupportedException. A shallow copy replicates primitive fields and object references, meaning the copied object still shares references to mutable nested objects with the original. To achieve a secure deep copy, developers must override the public clone method and manually clone all nested mutable structures to prevent shared state side effects.');
